# Generated by Django 3.2.7 on 2021-09-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField()),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
